settings:
  server-id: '00000000'
  channel: 'test'
  username: 'username'
  email: 'email@example.com'
  password: 'password'
  debug: false
  relay_cancelled_messages: true
  messages:
    chat: true
    join: true
    leave: true
    death: false
  if_vanished:
    chat: false
    join: false
    leave: false
    death: false
  templates:
    discord:
      chat_message: '<%u> %m'
      player_join: '%u joined the server'
      player_leave: '%u left the server'
      player_death: '%r'
    minecraft:
      chat_message: '<%u&b(discord)&r> %m'
